name: Python Flask Rest API

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository and Set up Python
      - uses: actions/checkout@v3
      - name: Setup python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Run a inline script
        run: python app.py
      - name: Python Pylint Github Actions for Code Analysis
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          find . -name 'app.py' -exec pylint {} \;
      - name: Run Unit-Test (pytest)
        run: |
          python -m pip install 
      - run: 'echo "This job status is ${{ job.status }}."'
