name: Python Flask Rest API

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository and Set up Python
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
